### ISSUE TITLE
Uploaded media filename 

### ISSUE THREAD

**Issue by AC17dollars** [ecastthapathali/ECAST-Website#7]
uploaded media filename should be named same as referencing primary key.

uploaded: elephant.png

should be saved as: member_photos/{user_uuid}.{file_extension}
eg: member_photos/f47ac10b-58cc-4372-a567-0e02b2c3d479.png

**Comment by nepalprastut** [comment]
Thanks, will look into this.

**Comment by AC17dollars** [comment]
#14 solves
